---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aws-accesskey-operator.lightjack.de
  resources:
  - iamaccesskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-accesskey-operator.lightjack.de
  resources:
  - iamaccesskeys/finalizers
  verbs:
  - update
- apiGroups:
  - aws-accesskey-operator.lightjack.de
  resources:
  - iamaccesskeys/status
  verbs:
  - get
  - patch
  - update
