apiVersion: aws-accesskey-operator.lightjack.de/v1alpha1
kind: IAMAccessKey
metadata:
  labels:
    app.kubernetes.io/name: aws-accesskey-operator
    app.kubernetes.io/managed-by: kustomize
  name: iamaccesskey-sample
spec:
  # TODO(user): Add fields here
