//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMAccessKey) DeepCopyInto(out *IAMAccessKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMAccessKey.
func (in *IAMAccessKey) DeepCopy() *IAMAccessKey {
	if in == nil {
		return nil
	}
	out := new(IAMAccessKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMAccessKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMAccessKeyList) DeepCopyInto(out *IAMAccessKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IAMAccessKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMAccessKeyList.
func (in *IAMAccessKeyList) DeepCopy() *IAMAccessKeyList {
	if in == nil {
		return nil
	}
	out := new(IAMAccessKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMAccessKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMAccessKeySpec) DeepCopyInto(out *IAMAccessKeySpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMAccessKeySpec.
func (in *IAMAccessKeySpec) DeepCopy() *IAMAccessKeySpec {
	if in == nil {
		return nil
	}
	out := new(IAMAccessKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMAccessKeyStatus) DeepCopyInto(out *IAMAccessKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMAccessKeyStatus.
func (in *IAMAccessKeyStatus) DeepCopy() *IAMAccessKeyStatus {
	if in == nil {
		return nil
	}
	out := new(IAMAccessKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMAdminCredentialsSecretRef) DeepCopyInto(out *IAMAdminCredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMAdminCredentialsSecretRef.
func (in *IAMAdminCredentialsSecretRef) DeepCopy() *IAMAdminCredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(IAMAdminCredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderConfig) DeepCopyInto(out *IAMProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderConfig.
func (in *IAMProviderConfig) DeepCopy() *IAMProviderConfig {
	if in == nil {
		return nil
	}
	out := new(IAMProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderConfigList) DeepCopyInto(out *IAMProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IAMProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderConfigList.
func (in *IAMProviderConfigList) DeepCopy() *IAMProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(IAMProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderConfigRef) DeepCopyInto(out *IAMProviderConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderConfigRef.
func (in *IAMProviderConfigRef) DeepCopy() *IAMProviderConfigRef {
	if in == nil {
		return nil
	}
	out := new(IAMProviderConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderConfigSpec) DeepCopyInto(out *IAMProviderConfigSpec) {
	*out = *in
	out.AdminCredentialsSecretRef = in.AdminCredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderConfigSpec.
func (in *IAMProviderConfigSpec) DeepCopy() *IAMProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(IAMProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderConfigStatus) DeepCopyInto(out *IAMProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderConfigStatus.
func (in *IAMProviderConfigStatus) DeepCopy() *IAMProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(IAMProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderGrant) DeepCopyInto(out *IAMProviderGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderGrant.
func (in *IAMProviderGrant) DeepCopy() *IAMProviderGrant {
	if in == nil {
		return nil
	}
	out := new(IAMProviderGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMProviderGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderGrantList) DeepCopyInto(out *IAMProviderGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IAMProviderGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderGrantList.
func (in *IAMProviderGrantList) DeepCopy() *IAMProviderGrantList {
	if in == nil {
		return nil
	}
	out := new(IAMProviderGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IAMProviderGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IAMProviderGrantSpec) DeepCopyInto(out *IAMProviderGrantSpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.AllowedUsernames != nil {
		in, out := &in.AllowedUsernames, &out.AllowedUsernames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IAMProviderGrantSpec.
func (in *IAMProviderGrantSpec) DeepCopy() *IAMProviderGrantSpec {
	if in == nil {
		return nil
	}
	out := new(IAMProviderGrantSpec)
	in.DeepCopyInto(out)
	return out
}
